(() => {
  "use strict";
  const VERSION=document.querySelector('meta[name="app-version"]')?.content||"dev";
  const views={home:document.querySelector("#homeView"),subject:document.querySelector("#subjectView"),exercise:document.querySelector("#exerciseView"),result:document.querySelector("#resultView")};
  const subjectGrid=document.querySelector("#subjectGrid"),categoryGrid=document.querySelector("#categoryGrid"),breadcrumbs=document.querySelector("#breadcrumbs");
  const subjectTitle=document.querySelector("#subjectTitle"),subjectDescription=document.querySelector("#subjectDescription"),subjectBadge=document.querySelector("#subjectBadge");
  const exerciseSubject=document.querySelector("#exerciseSubject"),moduleTitle=document.querySelector("#moduleTitle"),moduleNote=document.querySelector("#moduleNote");
  const questionKind=document.querySelector("#questionKind"),questionContext=document.querySelector("#questionContext"),questionPrompt=document.querySelector("#questionPrompt"),answerArea=document.querySelector("#answerArea");
  const feedback=document.querySelector("#feedback"),feedbackTitle=document.querySelector("#feedbackTitle"),feedbackText=document.querySelector("#feedbackText"),nextBtn=document.querySelector("#nextBtn");
  const progressText=document.querySelector("#progressText"),progressTrack=document.querySelector("#progressTrack"),progressBar=document.querySelector("#progressBar");
  const resultTitle=document.querySelector("#resultTitle"),resultScore=document.querySelector("#resultScore"),resultMessage=document.querySelector("#resultMessage");
  const exerciseBackBtn=document.querySelector("#exerciseBackBtn"),againBtn=document.querySelector("#againBtn"),resultBackBtn=document.querySelector("#resultBackBtn");
  let curriculum=null,currentSubject=null,currentCategory=null,currentModule=null,queue=[],index=0,correct=0,scored=0,answered=false;
  let state=loadState();

  const normalize=v=>String(v).toLowerCase().replace(/[’]/g,"'").replace(/\s+/g," ").trim().replace(/[.,!?;:]+$/g,"");
  async function fetchJson(path){const r=await fetch(`${path}?v=${encodeURIComponent(VERSION)}`,{cache:"no-store"});if(!r.ok)throw new Error(`${path} kon niet worden geladen.`);return r.json();}
  function validateCurriculum(value){if(!value||!Array.isArray(value.subjects))throw new Error("De leerstructuur is ongeldig.");return value;}
  function validateModule(value){if(!value||!value.id||!Array.isArray(value.questions))throw new Error("Deze oefenmodule is ongeldig.");const ids=new Set();for(const item of value.questions){if(!item.id||ids.has(item.id)||!item.type||!item.prompt)throw new Error(`Ongeldige vraag in ${value.id}.`);ids.add(item.id);}return value;}
  function setView(name){for(const [key,el] of Object.entries(views))el.hidden=key!==name;window.scrollTo({top:0,behavior:"smooth"});}
  function sorted(items){return [...items].filter(x=>x.enabled!==false).sort((a,b)=>(a.order??99)-(b.order??99));}
  function categoryCount(subject){return sorted(subject.categories||[]).length;}
  function statFor(id){return state.moduleStats?.[id]||{completed:0,correct:0,scored:0};}
  function renderHome(){currentSubject=null;currentCategory=null;breadcrumbs.hidden=true;subjectGrid.innerHTML="";for(const subject of sorted(curriculum.subjects)){const b=document.createElement("button");b.type="button";b.className="subject-card";b.dataset.accent=subject.accent||"blue";b.innerHTML=`<span class="subject-icon"></span><h2></h2><p></p><span class="subject-meta"><span>${categoryCount(subject)} onderwerpen</span><span>Open →</span></span>`;b.querySelector(".subject-icon").textContent=subject.icon||"•";b.querySelector("h2").textContent=subject.title;b.querySelector("p").textContent=subject.description||"";b.addEventListener("click",()=>openSubject(subject.id));subjectGrid.append(b);}setView("home");}
  function renderBreadcrumbs(items){breadcrumbs.innerHTML="";items.forEach((item,i)=>{if(i){const s=document.createElement("span");s.className="crumb-sep";s.textContent="/";breadcrumbs.append(s);}if(item.action){const b=document.createElement("button");b.type="button";b.className="crumb-button";b.textContent=item.label;b.addEventListener("click",item.action);breadcrumbs.append(b);}else{const s=document.createElement("span");s.textContent=item.label;breadcrumbs.append(s);}});breadcrumbs.hidden=false;}
  function openSubject(id){const subject=curriculum.subjects.find(x=>x.id===id&&x.enabled!==false);if(!subject)return;currentSubject=subject;currentCategory=null;subjectTitle.textContent=subject.title;subjectDescription.textContent=subject.description||"";subjectBadge.textContent="VAK";categoryGrid.innerHTML="";for(const category of sorted(subject.categories||[])){const stats=statFor(category.id);const b=document.createElement("button");b.type="button";b.className="category-card";const icon=document.createElement("span");icon.className="category-icon";icon.textContent=category.icon||"•";const title=document.createElement("h2");title.textContent=category.title;const copy=document.createElement("p");copy.textContent=stats.completed?`${stats.completed} vragen/opdrachten gemaakt`:'Klaar om te starten';const meta=document.createElement("span");meta.className="category-meta";meta.innerHTML=`<span>${stats.completed?"Verder oefenen":"Start"}</span><span>→</span>`;b.append(icon,title,copy,meta);b.addEventListener("click",()=>openCategory(category.id));categoryGrid.append(b);}renderBreadcrumbs([{label:"Vakken",action:renderHome},{label:subject.title}]);setView("subject");}
  async function openCategory(id){const category=(currentSubject?.categories||[]).find(x=>x.id===id);if(!category)return;currentCategory=category;try{currentModule=validateModule(await fetchJson(`./data/modules/${category.file}`));startSession();}catch(error){console.error(error);alert(error.message||"Oefening kon niet worden geladen.");}}
  function freshQuestions(module){const count=Math.min(module.sessionLength||10,module.questions.length);const seen=Array.isArray(state.seen?.[module.id])?state.seen[module.id].filter(id=>module.questions.some(q=>q.id===id)):[];let remaining=module.questions.filter(q=>!seen.includes(q.id));if(remaining.length<count){remaining=[...remaining,...module.questions.filter(q=>seen.includes(q.id))];}const shuffled=[...remaining].sort(()=>Math.random()-.5);const chosen=shuffled.slice(0,count);state.seen=state.seen||{};let nextSeen=[...seen,...chosen.map(q=>q.id)];if(new Set(nextSeen).size>=module.questions.length)nextSeen=[];state.seen[module.id]=[...new Set(nextSeen)];saveState(state);return chosen;}
  function startSession(){queue=freshQuestions(currentModule);index=0;correct=0;scored=0;answered=false;exerciseSubject.textContent=currentSubject?.title||"";moduleTitle.textContent=currentModule.title;moduleNote.hidden=!currentModule.note;moduleNote.textContent=currentModule.note||"";renderBreadcrumbs([{label:"Vakken",action:renderHome},{label:currentSubject.title,action:()=>openSubject(currentSubject.id)},{label:currentCategory.title}]);setView("exercise");renderQuestion();}
  function updateProgress(done=false){const total=queue.length||1;const completed=done?Math.min(index+1,total):index;const pct=Math.round(completed/total*100);progressText.textContent=`${Math.min(index+1,total)} / ${total}`;progressBar.style.width=`${pct}%`;progressTrack.setAttribute("aria-valuenow",String(pct));progressTrack.setAttribute("aria-valuetext",`${pct}% voltooid`);}
  function typeLabel(type){return ({'multiple-choice':'Meerkeuze','true-false':'Juist of fout','input':'Schrijf je antwoord','number':'Rekenen','open':'Doe-opdracht'})[type]||'Oefening';}
  function clearFeedback(){feedback.hidden=true;feedback.className="feedback-box";feedbackTitle.textContent="";feedbackText.textContent="";nextBtn.hidden=true;}
  function renderQuestion(){const item=queue[index];if(!item){finish();return;}answered=false;clearFeedback();questionKind.textContent=typeLabel(item.type);questionPrompt.textContent=item.prompt;questionContext.hidden=!item.context;questionContext.textContent=item.context||"";answerArea.innerHTML="";updateProgress(false);if(item.type==='multiple-choice')renderChoices(item,item.options);else if(item.type==='true-false')renderChoices(item,['Juist','Fout']);else if(item.type==='input'||item.type==='number')renderInput(item);else if(item.type==='open')renderOpen(item);else throw new Error(`Onbekend vraagtype: ${item.type}`);}
  function renderChoices(item,values){const grid=document.createElement("div");grid.className="choice-grid";for(const value of values){const b=document.createElement("button");b.type="button";b.className="choice-button";b.textContent=value;b.addEventListener("click",()=>{let expected=item.type==='true-false'?(item.answer?'Juist':'Fout'):item.answer;answerScored(item,value===expected,b,expected);});grid.append(b);}answerArea.append(grid);}
  function renderInput(item){const form=document.createElement("form");form.className="answer-form";const input=document.createElement("input");input.className="answer-input";input.autocomplete="off";input.inputMode=item.type==='number'?'numeric':'text';input.setAttribute("aria-label","Jouw antwoord");const button=document.createElement("button");button.type="submit";button.className="primary-button";button.textContent="Controleer";form.append(input,button);form.addEventListener("submit",e=>{e.preventDefault();if(answered)return;const value=input.value.trim();if(!value)return;const accepted=item.accepted||[item.answer];let ok;if(item.type==='number')ok=Number(String(value).replace(',','.'))===Number(item.answer);else ok=accepted.some(x=>normalize(x)===normalize(value));answerScored(item,ok,null,item.displayAnswer??item.answer);input.disabled=true;button.disabled=true;});answerArea.append(form);setTimeout(()=>input.focus(),0);}
  function renderOpen(item){const box=document.createElement("div");box.className="open-task";box.textContent="Voer de opdracht uit. Klik daarna op ‘Klaar’ om een tip of controlepunt te bekijken.";const button=document.createElement("button");button.type="button";button.className="primary-button";button.style.marginTop="12px";button.textContent="Klaar · toon tip";button.addEventListener("click",()=>{if(answered)return;answered=true;feedback.hidden=false;feedback.className="feedback-box correct";feedbackTitle.textContent="Goed gedaan!";feedbackText.textContent=item.tip||item.explanation||"Denk even na over wat goed ging en wat je nog kunt verbeteren.";nextBtn.hidden=false;updateProgress(true);recordQuestion(false,false);});box.append(document.createElement("br"),button);answerArea.append(box);}
  function answerScored(item,ok,button,expected){if(answered)return;answered=true;scored++;if(ok)correct++;const buttons=answerArea.querySelectorAll(".choice-button");buttons.forEach(b=>{b.disabled=true;if(b.textContent===String(expected))b.classList.add("correct");});if(button&&!ok)button.classList.add("wrong");feedback.hidden=false;feedback.className=`feedback-box ${ok?'correct':'incorrect'}`;feedbackTitle.textContent=ok?'Juist!':'Nog niet juist.';feedbackText.textContent=item.explanation||(!ok?`Het juiste antwoord is ${expected}.`:'');nextBtn.hidden=false;updateProgress(true);recordQuestion(true,ok);}
  function recordQuestion(isScored,ok){state.completed=(state.completed||0)+1;if(isScored){state.correct=(state.correct||0)+(ok?1:0);}const id=currentModule.id;const s=state.moduleStats[id]||{completed:0,correct:0,scored:0};s.completed++;if(isScored){s.scored++;if(ok)s.correct++;}state.moduleStats[id]=s;saveState(state);window.dispatchEvent(new CustomEvent('oefenen4e:progress'));}
  function next(){if(!answered)return;index++;if(index>=queue.length)finish();else renderQuestion();}
  function finish(){setView("result");const openCount=queue.length-scored;const pct=scored?Math.round(correct/scored*100):null;resultTitle.textContent=pct===100?'Sterk gewerkt!':pct!==null&&pct>=75?'Goed bezig!':'Oefenronde klaar!';resultScore.textContent=scored?`${correct} van ${scored} controleerbare vragen juist${openCount?` · ${openCount} doe-opdracht${openCount===1?'':'en'}`:''}`:`${openCount} doe-opdracht${openCount===1?'':'en'} afgerond`;resultMessage.textContent=pct===100?'Alles wat automatisch gecontroleerd kon worden, was juist.':pct!==null&&pct>=75?'Mooie ronde. Nog een keer oefenen zorgt voor extra zekerheid.':pct!==null?'Bekijk de uitleg rustig en probeer later opnieuw.':'Goed gedaan. Bij spreek- en schrijfopdrachten helpt feedback van een leerkracht of klasgenoot.';}
  exerciseBackBtn.addEventListener('click',()=>openSubject(currentSubject.id));nextBtn.addEventListener('click',next);againBtn.addEventListener('click',startSession);resultBackBtn.addEventListener('click',()=>openSubject(currentSubject.id));
  window.LearningEngine={async init(){curriculum=validateCurriculum(await fetchJson('./data/curriculum.json'));renderHome();},goHome:renderHome,getCurriculum:()=>curriculum};
})();
